<h1><i class="fas fa-cogs"></i> Panneau d'administration</h1>

<form>
	<h2><i class="fas fa-pen-fancy"></i> <a href="add_post.php">Rédiger un nouveal article</a></h2>
	<table>
		<thead>
			<td>Titre</td>
			<td>Article</td>
			<td>Auteur</td>
			<td>Catégorie</td>
			<td>Actions</td>
		</thead>
		<tbody>
			<?php foreach ($posts as $post) :?>
					<tr>
						<td><a href="article.php?ID=<?= $post['ID']?>"><?= $post['title'] ?></a>
						</td>
						<td><?php
							if ((strlen($post['smallContent'])) > 25){
								echo $post['smallContent']." [...]";
							} else { echo $post['smallContent']; }
							
							?>
						</td>
						<td class="author"><?= $post['firstName']." ".$post['lastName'] ?>
						</td>
						<td><?= $post['category']?></td>
						<td><a href="edit_post.php?ID=<?= $post['ID'] ?>"><i class="fas fa-pen-fancy"></i></a><a href="delete_post.php?ID=<?= $post['ID'] ?>"><i class="fas fa-trash"></i></a></td>
					</tr>
				<?php endforeach ?>
		</tbody>
	</table>

</form>