<form action="register.php" method="post">

<label for="user">User Name</label>
<input type='text' id="user" name="user" placeholder="votre nom de connexion" required>
<label for="email">Votre Email<input type="email" id="email" name="email"></label>
<label for="password">Mot de passe<input type="text" style="-webkit-text-security: circle;" name="password" id="password" placeholder="********" required></label>
</form>

<p>Si vous n'êtes pas déjà inscrit, <a href="login.php">c'est par ici !</a></p>