<article ID="CV">
    <header>
    <div class="container">
            <h1>Loic Geny</h1>
			<main>
                <p><strong>Développeur web</strong></p>
                <p>Responsive Web Design</p>
                <p>Wordpress</p>
                <p>Développeur Front-End et Back-End</p>
                <p>GameDesign / Programmation de jeux-vidéos</p>
                <p>Programmation orientée Objet</p>
                <p>Connaissances SoftWare avancées(Windows, Linux) et Hardware (Desktop et serveur)</p>
                <p>Veille Technologique</p>
                <small>Ancien Infirmier en bloc opératoire de chirurgie cardiaque. Tout ce que vous voyez sur ce site a été programmé et réalisé par mes soins, sauf mention contraire.</small>
                <a href="mailto:loic.geny@gmail.com" class="btn">Press Start to contact</a>
                <a href="#work"  class="btn">Mes travaux</a>
			</main>
			<div class="modern-separator"><div class="separator"></div></div>
			<div class="gb-separator hidden"><div class="pixelated"></div><div class="pixelated"></div><div class="pixelated"></div><div class="pixelated"></div><div class="pixelated"></div><div class="pixelated"></div><div class="pixelated"></div><div class="pixelated"></div><div class="pixelated"></div><div class="pixelated"></div><div class="pixelated"></div><div class="pixelated"></div><div class="pixelated"></div><div class="pixelated"></div><div class="pixelated"></div><div class="pixelated"></div><div class="pixelated"></div><div class="pixelated"></div><div class="pixelated"></div><div class="pixelated"></div><div class="pixelated"></div><div class="pixelated"></div><div class="pixelated"></div><div class="pixelated"></div></div>

		</div>
	</header>
	<div class="container">
		<section id="skills">
            <div id="langages">
				<h2>Languages</h2>
				<ul>
					<li><div class="card" id="html5"><i class="icon-html5-alt" #icone></i></div></li><!--
					--><li><div class="card" id="css3"><i class="icon-css3-alt"></i></div></li><!--
					--><li><div class="card" id="js"><i class="icon-javascript-alt"></i></div></li><!--
					--><li><div class="card" id="php"><i class="icon-php-alt"></i></div></li><!--
					--><li><div class="card" id="mysql"><i class="icon-mysql"></i></div></li><!--
					--><li><div class="card" id="csharp"><i class="icon-csharp"></i></div></li>
				</ul>
            </div><!--    
            --><div class="none">
                    <?php include 'parts/theseparator.html'; ?>
            </div><!--
        --><div id="tools">
                <h2>CMS et Frameworks</h2>
				<ul>
					<li><div class="card" id="wordpress"><i class="icon-wordpress"></i></div></li>
					<li><div class="card" id="wordpress"><i class="icon-laravel"></i></div></li>
					<li><div class="card" id="bootstrap"><i class="icon-bootstrap"></i></div></li>
				</ul>
            </div>
            <?php include 'parts/theseparator.html'; ?>
            <div id="logiciel">
                <h2>Logiciels</h2>
                <ul>
                    <li><div class="card" id="unity"><i class="icon-unity"></i></div></li>
                    <li><div class="card" id="photoshop"><i class="fab fa-adobe"></i></div></li>
                    <li><div class="card" id="word"><i class="fas fa-file-word"></i></div></li>
                </ul> 
            </div>
	        <?php include 'parts/theseparator.html'; ?>
		</section>
        <section id="work">
            <h2>Projets</h2>
            <!-- Doudou's Slider -->
            <?php include 'parts/slider.html'; ?>
			<!-- Doudou's Slider -->
        </section>
   </div>
   <div><small>Tools Icones and Frameworks Icones provided <a href="http://fizzed.com/oss/font-mfizz/icon-laravel">by Font Mfizz</a> and <a href="http://www.fontawesome.com">Font Awesome</a></small></div>
</article>