<h1>Mes créations</h1>

<article>
	<h2>Space PiouPiou</h2>
	<h3>Statut : en cours ...</h3>
	<p>Piou Piou est une noble canari de l'espace dont sa seule mission est de libérer son chère et tendre de l'horrible envahisseur ChaLien ... Arriverez vous à aller le plus loin ?</p>
	<div class="videocontainer">
		<iframe width="560" height="315" src="https://www.youtube.com/embed/SlczqQ9w8gc" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
	</div>
	<a href="https://japandoudou.com/2018/08/03/enfin-la-demo-space-pioupiou-the-demo/">Un lien de téléchargement est disponible ici</a>
</article>

<article>
	<h2>ChiFouMi</h2>
	<h3>Statut : Fini</h3>
	<a href="parts/shifumi.html">
		<p>Petit projet HTML5 CSS3 et Javascript basique, c'est un Papier Cailloux Ciseaux Lezard Spock classique réalisé dans le cadre de l'apprentissage de la programmation</p>
	</a>
</article>

<article>
	<h2>Memory</h2>
	<h3>Statut : Fini</h3>
	<a href="memory.php">
		<p>Projet HTML5 CSS3 et Javascript également, c'est mon Memory Game réalisé dans le cadre de l'apprentissage de la programmation. Petit défi personnel pour voir si j'avais les compétences pour réaliser ceci sans aide.</p>
	</a>
</article>

<article>
	<h2>Mon CV numérique</h2>
	<a href="cv.php">
		<p>Mon CV version "OnLine" avec du responsive et du JS. Quelques easters Eggs par ci par là également.<br>
		Au cours de la formation on a pu voir beaucoup de choses très abstraite, notamment la POO. Je n'ai pas l'occasion de vous montrer ce que j'en ai retenu ici, peut être faut-il se référer à SpacePiouPiou?
		</p>
	</a>
</article>
