	<?php if($error == "already") :?>
		<p class="error">Ce nom d'utilisateur est déjà pris ...</p>
	<?php endif ?>

<form action="register.php" method="post" id="register">


	<fieldset>
		<legend><label for="user">User Name</label></legend>
		<input type='text' id="user" name="user" placeholder="votre nom de connexion" required>
	</fieldset>

	<fieldset>
		<legend>
			<label for="email">Votre mail</label>
		</legend>
		<input type="email" id="email" name="email">
	</fieldset>

	<fieldset>
		<legend>
			<label for="password">Mot de passe</label>
		</legend>
		<input type="text" minlength="6" style="-webkit-text-security: circle;" name="password" id="password" placeholder="********" required>
	</fieldset>

	<button class="btn">S'inscrire !</button>
</form>

<p>Si vous êtes déjà inscrit, <a href="login.php" class="btn">c'est par ici !</a></p>